// USERS
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_EXCEPT_ID = 'FETCH_USERS_EXCEPT_ID';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// TASKS
export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASKS_ERROR = 'FETCH_TASKS_ERROR';
export const FETCH_TASKS_BY_USER = 'FETCH_TASKS_BY_USER';
export const ADD_TASK = 'ADD_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASKS = 'DELETE_TASKS';

// SERVICES
export const FETCH_SERVICES = 'FETCH_SERVICES';
export const FETCH_SERVICES_ERROR = 'FETCH_SERVICES_ERROR';
export const FETCH_SERVICES_BY_USER = 'FETCH_SERVICES_BY_USER';
export const ADD_SERVICE = 'ADD_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const DELETE_SERVICES = 'DELETE_SERVICES';

// BUSINESSES
export const FETCH_BUSINESSES = 'FETCH_BUSINESSES';
export const FETCH_BUSINESSES_ERROR = 'FETCH_BUSINESSES_ERROR';
export const DELETE_BUSINESSES = 'DELETE_BUSINESSES';
export const ADD_BUSINESS = 'ADD_BUSINESS';
export const UPDATE_BUSINESS = 'UPDATE_BUSINESS';

// MESSAGES
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_MESSAGES_ERROR = 'FETCH_MESSAGES_ERROR';
export const FETCH_MESSAGES_SR = 'FETCH_MESSAGES_SR';

// SETTING
export const FETCH_SETTINGS = 'FETCH_SETTINGS';
export const FETCH_SETTINGS_ERROR = 'FETCH_SETTINGS_ERROR';

// PROFILE
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_ERROR = 'FETCH_PROFILE_ERROR';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';
export const UPDATE_SECURITY = 'UPDATE_SECURITY';
export const SET_PROFILE_LOADING = 'SET_PROFILE_LOADING';
export const UPDATE_PROFILE_STATE = 'UPDATE_PROFILE_STATE';
export const UPDATE_NOTIFICATIONS_STATE = 'UPDATE_NOTIFICATIONS_STATE';
export const UPDATE_SECURITY_STATE = 'UPDATE_SECURITY_STATE';