// TASKS
export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASKS_ERROR = 'FETCH_TASKS_ERROR';
export const ADD_TASK = 'ADD_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASKS = 'DELETE_TASKS';

// BUSINESSES
export const FETCH_BUSINESSES = 'FETCH_BUSINESSES';
export const FETCH_BUSINESSES_ERROR = 'FETCH_BUSINESSES_ERROR';
export const DELETE_BUSINESSES = 'DELETE_BUSINESSES';
export const ADD_BUSINESS = 'ADD_BUSINESS';
export const UPDATE_BUSINESS = 'UPDATE_BUSINESS';