// TASKS
export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASKS_ERROR = 'FETCH_TASKS_ERROR';

// BUSSINESS
export const FETCH_BUSINESSES = 'FETCH_BUSINESSES';
export const FETCH_BUSINESSES_ERROR = 'FETCH_BUSINESSES_ERROR';
export const DELETE_BUSINESSES = 'DELETE_BUSINESSES';
export const ADD_BUSINESS = 'ADD_BUSINESS';
export const UPDATE_BUSINESS = 'UPDATE_BUSINESS';